spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/game?createDatabaseIfNotExist=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    schema: classpath*:schema-mysql.sql
    initialization-mode: always

logging:
  level:
    sql: trace
