spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    username: ems
    password: 123456
    schema: classpath*:schema-h2.sql
    url: jdbc:h2:mem:ems

logging:
  level:
    sql: trace
